version: '2'
services:
  gatling-runner:
    image: <id>.dkr.ecr.eu-west-1.amazonaws.com/gatling-runner:latest
    command: -r <bucketname>
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/gatling-runner
        awslogs-region: eu-west-1
        awslogs-stream-prefix: gatling-runner
