version: '2'
services:
  gatling-runner:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/gatling-runner:latest
    command: -r ${AWS_REPORT_BUCKET}
    environment:
      - GATLING_NR_USERS=${GATLING_NR_USERS}
      - GATLING_MAX_DURATION=${GATLING_MAX_DURATION}
      - GATLING_RAMPUP_TIME=${GATLING_RAMPUP_TIME}
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/gatling-runner
        awslogs-region: eu-west-1
        awslogs-stream-prefix: gatling-runner
