{
 "title": "LoadTest",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Node $tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT count FROM \"gatling\" WHERE $timeFilter AND \"request\" = 'allRequests' AND \"status\"='all' group by request\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "All req",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(count) FROM \"gatling\" WHERE $timeFilter AND \"request\" = 'allRequests' AND \"status\"='all' group by time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors v Passes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "All Passes",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(count) FROM \"gatling\" WHERE $timeFilter AND (\"request\" = 'allRequests' AND \"status\" = 'ok') group by time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "All Errors",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(count) FROM \"gatling\" WHERE $timeFilter AND (\"request\" = 'allRequests' AND \"status\" = 'ko') group by time(1s)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "Pass $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count FROM \"gatling\" WHERE $timeFilter AND (\"request\" = 'allRequests' AND \"status\" = 'ok') group by request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Error $tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count FROM \"gatling\" WHERE $timeFilter AND (\"request\" = 'allRequests' AND \"status\" = 'ko') group by request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latencies: Percentiles & Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "percentiles50",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles50\") FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles50" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "percentiles95",
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles95\") FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "percentiles99",
     "measurement": "gatling",
     "query": "SELECT sum(\"percentiles99\") FROM \"gatling\" WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok') AND $timeFilter group by time(1s)",
     "select": [
      [
       { "params": [ "percentiles99" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Individual Requests (50% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles50\" FROM \"gatling\" WHERE (\"request\" <> 'allRequests') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "=", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "Individual Requests (95% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles95\" FROM \"gatling\" WHERE (\"request\" = 'allRequests') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "Individual Requests (99% Line)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "gatling",
     "query": "SELECT \"percentiles99\" FROM \"gatling\" WHERE (\"request\" = 'allRequests') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "percentiles95" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  }
 ]
}